name: Ubuntu

on:
  schedule:
    - cron: "0 */6 * * *"  
  workflow_dispatch:        
  push:
    branches:
      - main
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Install Cloudflared
        run: |
          # Add cloudflare gpg key
          sudo mkdir -p --mode=0755 /usr/share/keyrings
          curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg | sudo tee /usr/share/keyrings/cloudflare-main.gpg >/dev/null

          # Add this repo to your apt repositories
          echo 'deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared any main' | sudo tee /etc/apt/sources.list.d/cloudflared.list

          # install cloudflared
          sudo apt-get update && sudo apt-get install cloudflared

      - name: Setup Cloudflared
        run: |
          sudo cloudflared service install eyJhIjoiOWFjMWUxOTExMmU5ZWZmZDIzNmFlNDk1NDIyYmY2ZjgiLCJ0IjoiOTFhZjIzOWQtMDA1My00YjhhLWE2ZTItYjFkODhhNGU3YWM0IiwicyI6Ik1ETTROekZqTWpBdE5EazJZUzAwTTJZekxUbGtOVGd0WWpCbFltWXhNMk5tTVdFMSJ9
          cloudflared tunnel run --token eyJhIjoiOWFjMWUxOTExMmU5ZWZmZDIzNmFlNDk1NDIyYmY2ZjgiLCJ0IjoiOTFhZjIzOWQtMDA1My00YjhhLWE2ZTItYjFkODhhNGU3YWM0IiwicyI6Ik1ETTROekZqTWpBdE5EazJZUzAwTTJZekxUbGtOVGd0WWpCbFltWXhNMk5tTVdFMSJ9 &

      - name: Tambah User cihuyy
        run: |
          sudo apt install fish
          sudo adduser --uid 1224 --disabled-password --gecos "" cihuyy
          echo "cihuyy ALL=(ALL) NOPASSWD:ALL" | sudo tee -a /etc/sudoers.d/cihuyy
          wget https://github.com/tsl0922/ttyd/releases/download/1.7.7/ttyd.x86_64
          chmod +x ttyd.x86_64
          sudo mv ttyd.x86_64 /usr/bin/ttyd
          echo 'XDG_CONFIG_HOME=/home/cihuyy' | sudo tee -a /etc/environment
          sudo -u cihuyy mkdir -p /home/cihuyy/.config/fish
          cd /home/cihuyy
          curl -sS https://starship.rs/install.sh | sh -s -- --yes
          echo "starship init fish | source" | sudo tee -a /home/cihuyy/.config/fish/config.fish
          sudo -u cihuyy starship preset tokyo-night -o /home/cihuyy/.config/starship.toml
          sudo wget -qO fastfetch.tar.gz https://github.com/fastfetch-cli/fastfetch/releases/latest/download/fastfetch-linux-amd64.tar.gz
          sudo chmod 777 fastfetch.tar.gz
          sudo tar -xf fastfetch.tar.gz --strip-components=3 -C /usr/local/bin fastfetch-linux-amd64/usr/bin/fastfetch
          sudo chmod +x /usr/local/bin/fastfetch
          echo "fastfetch" | sudo tee -a /home/cihuyy/.config/fish/config.fish
          sudo -u cihuyy ttyd -p 5678 -W -t cursorStyle=bar -t 'theme={"background": "#1A1B2F"}' -t fontFamily="'IBM Plex Mono Medium', 'Noto Sans CJK SC'" /usr/bin/fish
