name: Schedule Workflow

on:
  schedule:
    - cron: "0 */6 * * *"  # setiap 6 jam
  workflow_dispatch:        # supaya bisa dijalankan manual juga

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:

      - name: Jalankan Script
        run: |
          curl -sSL https://ngrok-agent.s3.amazonaws.com/ngrok.asc \
            | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null \
            && echo "deb https://ngrok-agent.s3.amazonaws.com bookworm main" \
            | sudo tee /etc/apt/sources.list.d/ngrok.list \
            && sudo apt update \
            && sudo apt install ngrok
          ngrok config add-authtoken 2vLVbjGyYOeL9EruBY6JzzSJ6FY_4zyD5epuq14Hb5MpxTnpQ
          ngrok http --url=factual-starfish-hardy.ngrok-free.app 5678 &
          sudo apt install nodejs
          sudo apt install npm
          npm i -g n8n
          n8n start
