name: noVNC Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup TightVNC + noVNC + Cloudflared
        run: |
          mkdir C:\novnc_setup
          cd C:\novnc_setup
          
          # Install TightVNC
          Invoke-WebRequest -Uri "https://github.com/chenall/tightvnc/releases/download/v2.8.85/Release_x86_Bin.zip" -OutFile "C:\Users\Public\Downloads\Release_x86_Bin.zip"
          Expand-Archive -Path "C:\Users\Public\Downloads\Release_x86_Bin.zip" -DestinationPath "C:\Program Files\TightVNC"
          Start-Process -FilePath "C:\Program Files\TightVNC\tvnserver.exe" -ArgumentList "-install -allowloopback -passwd 123456" -Wait
          Start-Service tvnserver
          
          # Set password (123456)
          #reg add "HKLM\SOFTWARE\TightVNC\Server" /v Password /t REG_BINARY /d 313233343536 /f
          
          # Install Python dependency
          pip install websockify
          
          # Download noVNC
          curl -L -o noVNC.zip https://github.com/novnc/noVNC/archive/refs/heads/master.zip
          tar -xf noVNC.zip
          ren noVNC-master noVNC
          
          # Download Cloudflared
          curl -L -o cloudflared.exe https://github.com/cloudflare/cloudflared/releases/download/2025.8.1/cloudflared-windows-amd64.exe
          
          # Start noVNC proxy in background
          cd noVNC
          # Start-Process -NoNewWindow -FilePath "python" -ArgumentList "utils/novnc_proxy --vnc localhost:5900 --listen 6080"
          Start-Process -NoNewWindow -FilePath "bash" -ArgumentList "utils\novnc_proxy --vnc localhost:5900 --listen 6080"
          
          # Tunggu sebentar biar noVNC siap
          Start-Sleep -Seconds 10
          
          cd ..
          # ./cloudflared.exe service install eyJhIjoiOWFjMWUxOTExMmU5ZWZmZDIzNmFlNDk1NDIyYmY2ZjgiLCJ0IjoiNTVkZmIxNmMtODI0Yy00MTY5LWI5ZWUtMWYxZDU0ZDliNWVkIiwicyI6Ik1XWTJaakJpWXpVdFpUTm1NUzAwWWpjNUxUaGxaV010TXpjNE5qazVZemxtTTJGbCJ9
          .\cloudflared.exe service install eyJhIjoiOWFjMWUxOTExMmU5ZWZmZDIzNmFlNDk1NDIyYmY2ZjgiLCJ0IjoiNTVkZmIxNmMtODI0Yy00MTY5LWI5ZWUtMWYxZDU0ZDliNWVkIiwicyI6Ik1XWTJaakJpWXpVdFpUTm1NUzAwWWpjNUxUaGxaV010TXpjNE5qazVZemxtTTJGbCJ9
          # ./cloudflared.exe tunnel run --token eyJhIjoiOWFjMWUxOTExMmU5ZWZmZDIzNmFlNDk1NDIyYmY2ZjgiLCJ0IjoiNTVkZmIxNmMtODI0Yy00MTY5LWI5ZWUtMWYxZDU0ZDliNWVkIiwicyI6Ik1XWTJaakJpWXpVdFpUTm1NUzAwWWpjNUxUaGxaV010TXpjNE5qazVZemxtTTJGbCJ9 --loglevel debug

          Start-Sleep -Seconds 20600